Repository blockstack/blockstack-browser, pull requests merged in 2018-05, with the labels that each got.

#1370 Mark Ken as maintainer
  README.md
Labels: chore

#1287 New readme instructions
  README.md
Labels: in progress

#1429 Use Node 8 in Docker build
  Dockerfile
Labels: bug
