Repository blockstack/blockstack-browser, pull requests merged in 2018-04, with the labels that each got.

#1224 Fixes broken link to /issues
  CONTRIBUTING.md
Labels: 30 minutes, bug

#1255 Adds warnings while registration pending
  app/js/profiles/components/registration/RegistrationSearchView.js
  app/js/wallet/SendPage.js
Labels: enhancement

#1272 Use cors-anywhere in the Dockerfile
  Dockerfile
Labels: bug

#1275 Fix authentication with empty profiles
  app/js/auth/components/AuthModal.js
  app/js/profiles/store/identity/actions.js
  app/js/utils/profile-utils.js
Labels: bug

#1277 Add ignores for express and styled-components to flowconfig
  .flowconfig
Labels: in progress

#1281 Minor updates to Coins meta data and app icon
  app/images/app-icon-coins-256x256.png
  app/images/app-icon-coins-512x512.png
  app/js/data/apps.js
Labels: in progress
